### ISSUE TITLE
[Lease] Swap only amounts != the Lease currency

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/nolus-money-market#56]
Issue Gamm Exact In transaction only for amounts != Lpn. Currently, opening a lease providing a downpayment in the same currency fails.

**Comment by metodi96** [comment]
Currently, the following instantiated leases are blocked on the dev network due to being opened with a down payment of the same currency type as the desired asset:

1. nolus14d3zf0r548p6y77cjj7xjzfre8p89wuakczkfq7xlx02qvcdxz6sck3sxa
2. nolus18y876fjzdrgy4ds7e6yyjks9mjuts7v65kuszuch0m5lrmg4ad5qt08vkz
3. nolus172hrsurlhluatnhcksql48g7kzgq7zuvjlkz75sg3k5kmn8xgrjq9a384v
4. nolus1udulklye7hr9gvkkrgqsl9gvu3v2ftt4ysvsamv69hlxqvkkzk7svpu5uu
5. nolus1kdv75c24ec3jzwm32w3xr393s34y68xj339j7f5s9rslt6ndstgsrg7tpu
6. nolus1jx8m47zzxnfnkc79hs60m269n3wtg8z2c7f3vj4m4xf0zkq060nse4pk0u
